INSERT INTO SUPPLIER(SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_LOCATION)
VALUES(1,'Twitterbridge', 'Guanmiao'),
(2,'Wikizz', 'Duwaktenggi'),
(3,'Jamia', 'Caicedonia'),
(4,'Tazz', 'Sigetec'),
(5,'Zooxo', 'Sadang Kulon'),
(6,'DabZ', 'Gangsha'),
(7,'Teklist', 'Granada'),
(8,'Bubbletube', 'Annan'),
(9,'Midel', 'Tbilisskaya'),
(10,'Meejo', 'Distracci�_n'),
(11,'Skipstorm', 'Ubay'),
(12,'Thoughtbridge', 'Burmakino'),
(13,'Skinte', 'Ojos de Agua'),
(14,'Realbridge', 'Vol�۪sk'),
(15,'Zoombox', 'Groblersdal'),
(16,'Miboo', 'Pangnirtung'),
(17,'Eimbee', 'Richards Bay'),
(18,'Talane', 'Alfta'),
(19,'Quamba', 'Ath'),
(20,'Jabberstorm', 'Gharyan'),
(21,'Youbridge', 'Cambanugoy'),
(22,'Rhybox', 'Bongao'),
(23,'Oozz', 'Hazlov'),
(24,'Wordify', 'Pura'),
(25,'Innotype', 'Aveiras de Cima'),
(26,'Yabox', 'Zhiqing Songduo'),
(27,'Eamia', 'Otradnoye'),
(28,'Yodo', 'Pasembon'),
(29,'Flashspan', 'Whitwell'),
(30,'Tanoodle', 'La Estrella'),
(31,'Eimbee', 'Sritanjung'),
(32,'Skinder', 'Wonorejo'),
(33,'Blognation', 'Bia��a'),
(34,'Photobug', 'Changchi'),
(35,'Jabbersphere', 'Pingwang'),
(36,'Kazio', 'Xin�۪an'),
(37,'Buzzshare', 'Maticmatic'),
(38,'Skimia', 'Ambilobe'),
(39,'Devpulse', 'Yuanhou'),
(40,'Rhycero', 'Biguo'),
(41,'Nlounge', 'Huangyang'),
(42,'Realblab', 'Saurimo'),
(43,'Aibox', 'Rovira'),
(44,'Tagpad', 'Angra dos Reis'),
(45,'Agimba', 'Ituber��'),
(46,'Shufflester', 'Buritizeiro'),
(47,'LiveZ', 'Chaihe'),
(48,'Kazio', 'Berlin'),
(49,'Trudoo', 'Chugur'),
(50,'Photolist', 'Kal�_via');
