INSERT INTO ADVERTISEMENT(AD_ID, AD_NAME, AD_DESCRIPTION) VALUES
(1,'20% off everything', 'save money today!'),
(2,'Buy 1 get 1 free', 'Blowout sale!'),
(3,'20% off everything', 'SAVE BIG!!'),
(4,'Buy 1 get 1 free', 'SAVINGS! SAVINGs! '),
(5,'10% off next purchase', 'save money today!'),
(6,'Free Shipping on everthing', 'Blowout sale!'),
(7,'20% off everything', 'SAVE BIG!!'),
(8,'Buy 1 get 1 free', 'SAVINGS! SAVINGs! '),
(9,'10% off next purchase', 'save money today!'),
(10,'Free Shipping on everthing', 'Blowout sale!'),
(11,'20% off everything', 'SAVE BIG!!'),
(12,'Buy 1 get 1 free', 'SAVINGS! SAVINGs! '),
(13,'10% off next purchase', 'save money today!'),
(14,'Free Shipping on everthing', 'Blowout sale!'),
(15,'20% off everything', 'SAVE BIG!!'),
(16,'Buy 1 get 1 free', 'SAVINGS! SAVINGs! '),
(17,'10% off next purchase', 'save money today!'),
(18,'Free Shipping on everthing', 'save money today!');
